import type { SourceRegistryEntry } from '@/lib/import/types';
import { SCHOOL_SOURCE_REGISTRY } from '@/lib/import/school-source-registry';

const RAW_SOURCE_REGISTRY: SourceRegistryEntry[] = [
  {
    province: '广东',
    year: 2023,
    title: '广东省2023年普通高考本科批次投档情况下载',
    officialUrl: 'https://eea.gd.gov.cn/attachment/0/526/526559/4221648.zip',
    sourceType: 'zip',
    granularity: 'group',
    sourceLevel: 'province-official',
    expectedGranularity: 'group',
    parserKey: 'guangdong',
    parserVersion: '1',
    subjectGroup: '',
    batch: '本科批',
  },
  {
    province: '广东',
    year: 2024,
    title: '广东省2024年普通高考本科批次投档情况',
    officialUrl: 'https://eea.gd.gov.cn/attachment/0/554/554636/4458330.zip',
    sourceType: 'zip',
    granularity: 'group',
    sourceLevel: 'province-official',
    expectedGranularity: 'group',
    parserKey: 'guangdong',
    parserVersion: '1',
    subjectGroup: '',
    batch: '本科批',
  },
  {
    province: '广东',
    year: 2025,
    title: '广东省2025年本科普通类（物理）投档情况',
    officialUrl: 'https://eea.gd.gov.cn/attachment/0/585/585886/4746786.pdf',
    sourceType: 'pdf',
    granularity: 'group',
    sourceLevel: 'province-official',
    expectedGranularity: 'group',
    parserKey: 'guangdong',
    parserVersion: '1',
    subjectGroup: '物理类',
    batch: '本科批',
  },
  {
    province: '江苏',
    year: 2023,
    title: '江苏省2023年普通类本科批次平行志愿投档线（物理等科目类）',
    officialUrl: 'https://www.jseea.cn/webfile/upload/2023/07-18/10-05-510166-183377989.xls',
    sourceType: 'xls',
    granularity: 'group',
    sourceLevel: 'province-official',
    expectedGranularity: 'group',
    parserKey: 'jiangsu',
    parserVersion: '1',
    subjectGroup: '物理类',
    batch: '本科批',
  },
  {
    province: '江苏',
    year: 2023,
    title: '江苏省2023年普通类本科批次平行志愿投档线（历史等科目类）',
    officialUrl: 'https://www.jseea.cn/webfile/upload/2023/07-18/10-05-510148-1404562985.xls',
    sourceType: 'xls',
    granularity: 'group',
    sourceLevel: 'province-official',
    expectedGranularity: 'group',
    parserKey: 'jiangsu',
    parserVersion: '1',
    subjectGroup: '历史类',
    batch: '本科批',
  },
  {
    province: '江苏',
    year: 2024,
    title: '江苏省2024年普通类本科批次平行志愿投档线（物理等科目类）',
    officialUrl: 'https://www.jseea.cn/webfile/upload/2024/07-18/11-00-490856-746889704.xls',
    sourceType: 'xls',
    granularity: 'group',
    sourceLevel: 'province-official',
    expectedGranularity: 'group',
    parserKey: 'jiangsu',
    parserVersion: '1',
    subjectGroup: '物理类',
    batch: '本科批',
  },
  {
    province: '江苏',
    year: 2024,
    title: '江苏省2024年普通类本科批次平行志愿投档线（历史等科目类）',
    officialUrl: 'https://www.jseea.cn/webfile/upload/2024/07-18/09-11-430408314109108.xls',
    sourceType: 'xls',
    granularity: 'group',
    sourceLevel: 'province-official',
    expectedGranularity: 'group',
    parserKey: 'jiangsu',
    parserVersion: '1',
    subjectGroup: '历史类',
    batch: '本科批',
  },
  {
    province: '江苏',
    year: 2025,
    title: '江苏省2025年普通高校招生普通类本科批次平行志愿投档线（物理等科目类）',
    officialUrl: 'https://www.jseea.cn/webfile/upload/2025/07-18/09-33-5302461102655621.pdf',
    sourceType: 'pdf',
    granularity: 'group',
    sourceLevel: 'province-official',
    expectedGranularity: 'group',
    parserKey: 'jiangsu',
    parserVersion: '1',
    subjectGroup: '物理类',
    batch: '本科批',
  },
  {
    province: '江苏',
    year: 2025,
    title: '江苏省2025年普通高校招生普通类本科批次平行志愿投档线（历史等科目类）',
    officialUrl: 'https://www.jseea.cn/webfile/upload/2025/07-18/09-33-380724-1917118608.pdf',
    sourceType: 'pdf',
    granularity: 'group',
    sourceLevel: 'province-official',
    expectedGranularity: 'group',
    parserKey: 'jiangsu',
    parserVersion: '1',
    subjectGroup: '历史类',
    batch: '本科批',
  },
  {
    province: '浙江',
    year: 2023,
    title: '浙江省2023年普通高校招生普通类第一段平行投档分数线表',
    officialUrl: 'https://www.zjzs.net/picture/0/plug-in/ueditor/jsp/upload/2023719/1689731170158052765.xls',
    sourceType: 'xls',
    granularity: 'major',
    sourceLevel: 'province-official',
    crossCheckUrls: ['https://www.zjzs.net/art/2023/7/19/art_45_2052.html'],
    expectedGranularity: 'major',
    parserKey: 'zhejiang',
    parserVersion: '1',
    subjectGroup: '综合',
    batch: '本科批',
  },
  {
    province: '浙江',
    year: 2024,
    title: '浙江省2024年普通高校招生普通类第一段平行投档分数线表',
    officialUrl: 'https://www.zjzs.net/attach/0/80bebb3cf9b743aa800299669b4c6db5.xls',
    sourceType: 'xls',
    granularity: 'major',
    sourceLevel: 'province-official',
    crossCheckUrls: ['https://www.zjzs.net/art/2024/7/21/art_45_9899.html'],
    expectedGranularity: 'major',
    parserKey: 'zhejiang',
    parserVersion: '1',
    subjectGroup: '综合',
    batch: '本科批',
  },
  {
    province: '浙江',
    year: 2025,
    title: '浙江省2025年普通高校招生普通类第一段平行投档分数线表',
    officialUrl: 'https://www.zjzs.net/attach/0/8d8d48bdfabe4347b73ccc6009f328e4.xls',
    sourceType: 'xls',
    granularity: 'major',
    sourceLevel: 'province-official',
    crossCheckUrls: ['https://www.zjzs.net/art/2025/7/21/art_45_11467.html'],
    expectedGranularity: 'major',
    parserKey: 'zhejiang',
    parserVersion: '1',
    subjectGroup: '综合',
    batch: '本科批',
  },
  {
    province: '山东',
    year: 2025,
    title: '山东省2025年普通类常规批第1次志愿投档情况表',
    officialUrl: 'https://www.sdzk.cn/Floadup/file/20250719/6388855130412530367357143.xls',
    sourceType: 'xls',
    granularity: 'major',
    sourceLevel: 'province-official',
    crossCheckUrls: [
      'https://www.sdzk.cn/NewsInfo.aspx?NewsID=6996',
      'https://www.sdzk.cn/Floadup/file/20250728/6388931521217170972235326.xls'
    ],
    expectedGranularity: 'major',
    gapPolicy: 'rank_only_waiting_score_ladder',
    parserKey: 'shandong',
    parserVersion: '1',
    subjectGroup: '综合',
    batch: '本科批',
  },
  {
    province: '山东',
    year: 2025,
    title: '山东省2025年夏季高考成绩一分一段表',
    officialUrl: 'https://www.sdzk.cn/Floadup/file/20250625/6388646133710894671069456.xls',
    sourceType: 'xls',
    granularity: 'major',
    sourceLevel: 'province-official',
    expectedGranularity: 'major',
    parserKey: 'shandong-score-ladder',
    parserVersion: '1',
    subjectGroup: '综合',
    batch: '本科批',
  },
  {
    province: '河北',
    year: 2025,
    title: '2025年河北省普通高校招生本科批-历史科目组合平行志愿投档情况统计',
    officialUrl: 'http://file.hebeea.edu.cn/files/article/2025/07/20250722214851_332.xlsx',
    sourceType: 'xlsx',
    granularity: 'major',
    sourceLevel: 'province-official',
    crossCheckUrls: ['https://www.hebeea.edu.cn/html/xxgl/tzgg/2025/0722-214933-402.html'],
    expectedGranularity: 'major',
    parserKey: 'hebei',
    parserVersion: '1',
    subjectGroup: '历史科目组合',
    batch: '本科批',
  },
  {
    province: '河北',
    year: 2025,
    title: '2025年河北省普通高校招生本科批-物理科目组合平行志愿投档情况统计',
    officialUrl: 'http://file.hebeea.edu.cn/files/article/2025/07/20250722214852_210.xlsx',
    sourceType: 'xlsx',
    granularity: 'major',
    sourceLevel: 'province-official',
    crossCheckUrls: ['https://www.hebeea.edu.cn/html/xxgl/tzgg/2025/0722-214933-402.html'],
    expectedGranularity: 'major',
    parserKey: 'hebei',
    parserVersion: '1',
    subjectGroup: '物理科目组合',
    batch: '本科批',
  },
  {
    province: '贵州',
    year: 2025,
    title: '贵州省2025年高考本科批第2次征集志愿投档情况（首选科目物理）',
    officialUrl: 'http://zsksy.guizhou.gov.cn/ygpt/tdqk/202507/P020250728609925730354.pdf',
    sourceType: 'pdf',
    granularity: 'major',
    sourceLevel: 'province-official',
    crossCheckUrls: ['http://zsksy.guizhou.gov.cn/ygpt/tdqk/202508/t20250819_88489425.html'],
    expectedGranularity: 'major',
    parserKey: 'guizhou',
    parserVersion: '1',
    subjectGroup: '物理类',
    batch: '本科批',
  },
  {
    province: '陕西',
    year: 2024,
    title: '2024年陕西省普通高等学校招生本科一批最终模拟/正式投档情况统计表（理工）',
    officialUrl: 'https://www.sneac.com/htm/2024/1BZS-LG.html',
    sourceType: 'html',
    granularity: 'institution',
    sourceLevel: 'province-official',
    crossCheckUrls: [
      'https://www.sneac.com/zt/xgkxsfwpt/lnsj.htm',
      'https://www.sneac.com/info/1019/17293.htm',
    ],
    expectedGranularity: 'institution',
    gapPolicy: 'institution_only_waiting_school_majors',
    parserKey: 'shaanxi',
    parserVersion: '1',
    subjectGroup: '物理类',
    batch: '本科批',
  },
  {
    province: '辽宁',
    year: 2024,
    title: '辽宁省2024年普通高等学校招生录取普通类本科批（历史学科类）投档最低分',
    officialUrl: 'https://www.lnzsks.com/lnzkbfiles/2024/2024gkbkptdxosiexie01w.zip',
    sourceType: 'zip',
    granularity: 'major',
    sourceLevel: 'province-official',
    crossCheckUrls: ['https://www.lnzsks.com/newsinfo/IMS_20240720_44109_OymtAPK6ag.htm'],
    expectedGranularity: 'major',
    parserKey: 'liaoning',
    parserVersion: '1',
    subjectGroup: '历史类',
    batch: '本科批',
  },
  {
    province: '辽宁',
    year: 2024,
    title: '辽宁省2024年普通高等学校招生录取普通类本科批（物理学科类）投档最低分',
    officialUrl: 'https://www.lnzsks.com/lnzkbfiles/2024/2024gkbktdxsiexieft02l.zip',
    sourceType: 'zip',
    granularity: 'major',
    sourceLevel: 'province-official',
    crossCheckUrls: ['https://www.lnzsks.com/newsinfo/IMS_20240720_44109_OymtAPK6ag.htm'],
    expectedGranularity: 'major',
    parserKey: 'liaoning',
    parserVersion: '1',
    subjectGroup: '物理类',
    batch: '本科批',
  },
  {
    province: '湖南',
    year: 2025,
    title: '湖南省2025年普通高校招生本科提前批采用平行志愿的其他类院校第一次投档分数线(普通类)',
    officialUrl: 'https://www.hneeb.cn/hnxxg/741/742/2025070903pt.xlsx',
    sourceType: 'xlsx',
    granularity: 'group',
    sourceLevel: 'province-official',
    crossCheckUrls: ['https://www.hneeb.cn/hnxxg/741/742/content_4454.html'],
    expectedGranularity: 'group',
    parserKey: 'hunan',
    parserVersion: '1',
    subjectGroup: '普通类',
    batch: '提前批',
  },
  {
    province: '山东',
    year: 2025,
    title: '山东省2025年普通类常规批第2次志愿投档情况表',
    officialUrl: 'https://www.sdzk.cn/Floadup/file/20250728/6388931521217170972235326.xls',
    sourceType: 'xls',
    granularity: 'major',
    sourceLevel: 'province-official',
    crossCheckUrls: ['https://www.sdzk.cn/NewsInfo.aspx?NewsID=7010'],
    expectedGranularity: 'major',
    gapPolicy: 'rank_only_waiting_score_ladder',
    parserKey: 'shandong',
    parserVersion: '1',
    subjectGroup: '综合',
    batch: '本科批',
  },
  {
    province: '贵州',
    year: 2025,
    title: '贵州省2025年高考普通类本科批投档情况（首选科目历史）',
    officialUrl: 'http://zsksy.guizhou.gov.cn/ygpt/tdqk/202507/P020250723361496543916.pdf',
    sourceType: 'pdf',
    granularity: 'major',
    sourceLevel: 'province-official',
    crossCheckUrls: ['http://zsksy.guizhou.gov.cn/ygpt/tdqk/202508/t20250819_88489425.html'],
    expectedGranularity: 'major',
    parserKey: 'guizhou',
    parserVersion: '1',
    subjectGroup: '历史类',
    batch: '本科批',
  },
  {
    province: '辽宁',
    year: 2025,
    title: '辽宁省2025年普通高等学校招生录取普通类本科批（物理学科类）投档最低分',
    officialUrl: 'https://www.lnzsks.com/lnzkbfiles/2025/2025gkbkptd...zip',
    sourceType: 'zip',
    granularity: 'major',
    sourceLevel: 'province-official',
    status: 'review',
    crossCheckUrls: ['https://www.lnzsks.com/'],
    expectedGranularity: 'major',
    gapPolicy: '',
    parserKey: 'liaoning',
    parserVersion: '1',
    subjectGroup: '物理类',
    batch: '本科批',
  },
  {
    province: '辽宁',
    year: 2025,
    title: '辽宁省2025年普通高等学校招生录取普通类本科批（历史学科类）投档最低分',
    officialUrl: 'https://www.lnzsks.com/lnzkbfiles/2025/2025gkbkptd...zip',
    sourceType: 'zip',
    granularity: 'major',
    sourceLevel: 'province-official',
    status: 'review',
    crossCheckUrls: ['https://www.lnzsks.com/'],
    expectedGranularity: 'major',
    gapPolicy: '',
    parserKey: 'liaoning',
    parserVersion: '1',
    subjectGroup: '历史类',
    batch: '本科批',
  },
];

export const SOURCE_REGISTRY: SourceRegistryEntry[] = RAW_SOURCE_REGISTRY.map((entry) => ({
  examCategory: 'gaokao',
  sourceScope: 'ingest',
  priority: entry.sourceLevel === 'province-official' ? 100 : 50,
  status: 'active',
  family: (
    entry.sourceType === 'zip'
      ? 'province-major-zip'
      : entry.sourceType === 'pdf' && entry.granularity === 'major'
        ? 'province-major-pdf'
        : entry.sourceType === 'pdf'
          ? 'province-group-pdf'
          : entry.sourceType === 'html' && entry.granularity === 'institution'
            ? 'province-institution-html'
            : entry.granularity === 'major'
              ? 'province-major-xls'
              : 'province-general'
  ),
  sourceId: `${entry.parserKey}:${entry.province}:${entry.year}:${entry.subjectGroup ?? 'all'}:${entry.officialUrl}`,
  ...entry,
}));

export function getSourcesByProvinceYear(province?: string, year?: number): SourceRegistryEntry[] {
  return SOURCE_REGISTRY.filter((item) => {
    if (province && item.province !== province) return false;
    if (year && item.year !== year) return false;
    return true;
  });
}

export function getSchoolIngestSources(_referenceYear = new Date().getFullYear()): SourceRegistryEntry[] {
  return SCHOOL_SOURCE_REGISTRY.map((item) => ({
    sourceId: `school:${item.schoolKey}:${item.officialUrl}:${Math.max(...item.coverageYears)}`,
    province: '全国',
    year: Math.max(...item.coverageYears),
    title: `${item.institutionName}本科招生官网`,
    officialUrl: item.officialUrl,
    sourceType: item.sourceType,
    granularity: 'major',
    examCategory: 'gaokao',
    sourceScope: 'ingest',
    sourceLevel: 'school-official',
    schoolKey: item.schoolKey,
    priority: item.priority,
    status: item.status,
    crossCheckUrls: item.crossCheckUrls,
    family: item.pageMode === 'filter-page' ? 'school-major-html-filtered' : 'school-major-html-static',
    parserKey: item.adapterKey,
    parserVersion: '1',
    subjectGroup: null,
    batch: null,
  }));
}

export function getAllIngestSources(referenceYear = new Date().getFullYear()): SourceRegistryEntry[] {
  return [...SOURCE_REGISTRY, ...getSchoolIngestSources(referenceYear)];
}
